application: every-mama-knows
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bootstrap
  static_dir: bootstrap
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /templates
  static_dir: templates
  
- url: /javascript
  static_dir: javascript
  
- url: /json
  static_dir: json
  
- url: /images
  static_dir: images

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /upload/.*
  script: upload.app

- url: /serve/.*
  script: upload.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
